SELECT SYSDATETIME() AS sdatetime,
       SYSDATETIMEOFFSET() AS sdatetmoffs,
       SYSUTCDATETIME() AS sUTCdtime,
       CURRENT_TIMESTAMP AS Currtmstmp,
       GETDATE() AS GetDT,
       GETUTCDATE() AS GetUTCDT,
       CURRENT_DATE AS Nuova;

SELECT CONVERT (DATE, SYSDATETIME()) AS sdatetime,
       CONVERT (DATE, SYSDATETIMEOFFSET()) AS sdatetmoffs,
       CONVERT (DATE, SYSUTCDATETIME()) AS sUTCdtime,
       CONVERT (DATE, CURRENT_TIMESTAMP) AS Currtmstmp,
       CONVERT (DATE, GETDATE()) AS GetDT,
       CONVERT (DATE, GETUTCDATE()) AS GetUTCDT,
       CURRENT_DATE AS Nuova;